# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
