# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_salesuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amtB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='amtH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='amtM',
            field=models.IntegerField(default=0),
        ),
    ]
