# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20160509_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
