# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costB',
            field=models.IntegerField(default=100, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='costH',
            field=models.IntegerField(default=300, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='costM',
            field=models.IntegerField(default=200, editable=False),
        ),
    ]
